<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MKGRAMEENNIDHI | Privacy Policy</title>
    <link rel="stylesheet" href="{{asset('assets/styles.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="box">
            <h1>Privacy Policy
            </h1>

            <p>
                We value safety and privacy of your personal data. We have formulated this Privacy Policy to
                make the users understand our process of collecting information and parameters for
                non-disclosure. This document is an electronic record in terms of Information Technology Act,
                2000 and rules there under as applicable and the amended provisions pertaining to electronic
                records in various statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not require any physical or digital
                signatures.
            </p>

            <h4>Basic Policy
            </h4>

            <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information
                Technology (Intermediaries guidelines) Rules, 2011 that require publishing the Rules and
                Regulations, Privacy Policy and Terms of Use for access or usage https://mkgrameennidhi.com.
            </p>

            <p>The domain name https://mkgrameennidhi.com (“Website”), is owned and operated by
                MkGrameen mutual benefit Nidhi Limited. (“Company”) a Private Company limited by shares,
                incorporated under the provisions of the Companies Act, 2012, and having its registered office ,
                Cs 2803, A Ward Near, Janata Bank, Shivaji Peth, Sane Guruji Vasahat, Kolhapur, Karvir,
                Maharashtra, India, 416011</p>

            <p>where such expression shall, unless repugnant to the context thereof, be deemed to include its
                respective representatives, administrators, employees, directors, officers, agents and their
                successors and assigns.
            </p>

            <p>For the purpose of this Privacy Policy (“Policy”), wherever the context so requires,
                The term ‘You’ &‘User’ shall mean any legal person or entity who register on our website
                including prospective clients or their relatives/friends, registered service providers,
                accessing or using the services provided on this Website, who is competent to enter
                into binding contracts, as per the provisions of the Indian Contract Act, 1872
                The terms ‘We’, ‘Us’& ‘Our’ shall mean the Website and/or the Company, as the context
                so requires.</p>
            <p>The terms ‘Party’ & ‘Parties’ shall respectively be used to refer to the User and the
                Company individually and collectively, as the context so requires.
                The headings of each section in this Policy are only for the purpose of organizing the
                various provisions under this Policy in an orderly manner, and shall not be used by either
                Party to interpret the provisions contained herein in any manner. Further, it is specifically
                agreed to by the Parties that the headings shall have no legal or contractual value.
                Additional Terms</p>
            <p>The use of the Website by the User is solely governed by this Policy as well as the Terms of Use
                of the Website (“Terms”, available at https://mkgrameennidhi.com/), and any modifications or
                amendments made thereto by the Company from time to time, at its sole discretion. Visiting the
                home page of the Website and/or using any of the services provided on the Website shall be
                deemed to signify the User’s unequivocal acceptance of this Policy and the aforementioned
                Terms, and the User expressly agrees to be bound by the same. The User expressly agrees and
                acknowledges that the Terms and Policy are co-terminus, and that expiry / termination of either
                one will lead to the termination of the other.</p>
            <p>The User unequivocally agrees that this Policy and the aforementioned Terms constitute a
                legally binding agreement between the User and the Company, and that the User shall be subject
                to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided
                by the Website, and that the same shall be deemed to be incorporated into the Terms, and shall
                be treated as part and parcel of the same. The User acknowledges and agrees that no signature
                or express act is required to make these Terms and the Policy binding on the User, and that the
                User’s act of visiting any part of the Website constitutes the User’s full and final acceptance of
                the Policy and the aforementioned Terms.
            </p>
            <p>The Parties expressly agree that the Company retains the sole and exclusive right to amend or
                modify the Policy and the aforementioned Terms without any prior permission or intimation to
                the User, and the User expressly agrees that any such amendments or modifications shall come
                into effect immediately. The User has a duty to periodically check the Policy and Terms, and stay
                updated on their policies.
            </p>
            <p>If the User continues to use the Website following such a change, the User will be deemed to
                have consented to any and all amendments / modifications made to the Policy and Terms. In so
                far as the User complies with the Policy and Terms, he/she is granted a personal, non-exclusive,
                non-transferable, revocable, limited privilege to enter access and use the Website.</p>
        </div>
    </div>




</body>

</html>